### ISSUE TITLE
Student

### ISSUE THREAD

**Issue by DavidAkaFunky** [neiist-dev/neiist-website#135]

**Comment by nelsontr** [comment]
### NEIIST Members

* Explanation of what it means to be a NEIIST member

* Call button for registered users, Login button for non-registered users

### [LEIC-A Summaries](https://resumos.leic.pt/)

* Ask for permission from the responsible parties

* Site icon

* Brief explanation of what the site is about

* Button to Visit Site and Visit Github

  * Maybe have contribution avatars?

### Schedule Generators

* There are two: [Horarios.dang.pt](https://horarios.dang.pt) and [Gerador-Horários-IST](https://web.tecnico.ulisboa.pt/joanasesinando/gerador-horarios/)

* Same bullet points as above

... More?

**Comment by nelsontr** [comment]
Closing the issue for now. Will reopen if further development or updates arise.
