### ISSUE TITLE
[Shop/Frontend] - Shoping Cart

### ISSUE THREAD

**Issue by DiogoSantoss** [neiist-dev/neiist-website#199]
The shoping cart will store the selected products
Checkout button will eventually integrate with a payment library (e.g. Stripe)
![image](https://user-images.githubusercontent.com/59585571/235894597-db64d667-f50d-4f83-b565-6453c8e49f74.png)

**Comment by nelsontr** [comment]
Closing the issue for now. Please reopen if further development or updates arise.
