### ISSUE TITLE
[Shop/Payment] - Research payment libraries

### ISSUE THREAD

**Issue by DiogoSantoss** [neiist-dev/neiist-website#200]
Research and test some payment libraries (e.g. [Stripe](https://stripe.com/en-gb-pt))

**Comment by beatrizp03** [comment]
# PAYMENT LIBRARIES
### [How do payments work with Stripe?](https://www.nerdwallet.com/article/small-business/what-is-stripe) 
### [How do APIs work?](https://tray.io/blog/how-do-apis-work)

Alguns dos exemplos que vi foram:  
- PAYPAL 
-- **Online transaction costs :** 3.49% + $0.49 per transaction
--Beat for : small business with low sales volume and consultants and companies that invoice clients
--**Payment methods** : Credit and debit cards, ACH payments, Pay in 4, Venmo, Google Pay

- STRIPE
--**Online transaction costs : 2.9% + $0.30 per transaction**
--Best for : High-volume e-commerce business with web development resources
--**Payment methods** : Credit and debit cards, ACH payments, Google Pay, Apple Pay, Microsoft Pay, various foreign payment methods

- SKRILL
-- You don’t have to pay any fees to send money to a bank account overseas with Skrill – another aspect that makes it a good payment method for international business.
--These are some additional fees:
    - International transfers are 4.99% per transaction.
    - Withdrawal from a bank account costs $5.50.
    - The annual prepaid card fee is $10.

- SQUARE
-- Square is our choice as the best credit card processor for small busssinesses. 
-- You pay a standard processing fee of 2.6% plus 10 cents on all contactless payments, swiped payments (including with magstripe cards), and payments with inserted ship cards. It costs 3.5% plus 15 cents to process manually keyed-in payments.

- VENMO
-- Venmo is one of the better options for peer-to-peer payments.
-- You have to pay $2.50 for an out-of-network ATM withdrawal, but most of its services are free.

- PAYONEER
-- Another good option for international payments. Payoneer allows single or mass payouts, as well as the ability to receive payments and withdraw funds. Payoneer also includes API support.
-- To withdraw funds from your local bank account with Payoneer, you will pay up to 2% above the market rate at the time of transaction. To withdraw funds from another bank account in the same currency, you will pay $1.50. To make payments to others who do not have a Payoneer account, you’ll pay a fee of 1% to 3% depending on the payment method (ACH, credit card, etc.).

- SHOPIFY
-- Shopify Payments allows you to start accepting online payments without integrating a third-party payment provider, it makes the process simpler than many other options.
-- Here is a breakdown of its e-commerce plans:
    - **Basic Shopify:** $29 per month; 2.9% + $0.30 per transaction
    - **Shopify:** $79 per month; 2.6% + $0.30 per transaction
    - **Advanced Shopify:** $299 per month; 2.4% + $0.30 per transaction
    - **Shopify Plus:** Starts at around $2,000 per month; $2.15 per transaction

**Comment by DiogoSantoss** [comment]
MBWay [website](https://www.mbway.pt/integradores-mb-way/) also lists some services that accept MBWay as a payment method.
Some examples are:
- [easypay](https://www.easypay.pt/)
0,25€ + 1.50% [source](https://www.easypay.pt/precos/)
- [lusopay](https://www.lusopay.com/)
0,07€ + 0.70% + IVA (with MBWay) [source](https://www.lusopay.com/)

**Comment by nelsontr** [comment]
https://developer.sibsapimarket.com/sandbox/node/4497

**Comment by nelsontr** [comment]
Closing the issue for now. Please reopen if further development or updates arise.
